apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-argo-ray-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["ray.io"]
    resources: ["rayjobs", "rayclusters", "rayservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-argo-ray-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-argo-ray-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-sa
  namespace: {{ .Release.Namespace }}
