
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recsys-gitops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/trlocne/end-to-end-recsys-movies.git
    targetRevision: main
    path: deployments/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
     
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /status
        - /operation

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: false   # KHÔNG prune root app — xóa child Application sẽ cascade xóa toàn cluster
      selfHeal: true
