apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakEyTURNeApPVFF5TURSYUZ3MDBOakEyTURNeE9UUXlNRFJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERDNmemg4OGxZMEpIY2NINGM5cS9HQjBPTzgxdWVDSkJTWDFqUU5JZHZzSDNFUy9UUgpWWXlIZmhzY3FTTWhZTHFESlVSSHB3bDBPenFSTTRKc2xBNGhkT3d3bld4Ly9zZXZpMTdxQ2FUQ0lwQkZYYVVjCjdWeVg4Q1BCUEFnV21Wc2xlbEFaSjF3SUdwRlk1V3J3cUIvYVlLbWxKWUNRRVIvYnJERGp4d05KVFh5RjFadHMKWGFJSEZxbEJpYzFTMXp1dHZkeW5LcE4vbmwvOTdqSkl6TG05NDJ2S05pdWZ5YnJMKzdpZTJvRW12bTQ5RE1BMApUYUdueGNrUVJ2UG1IUnlhcHNMZElTZ2JJMnMrS0N1cXJWUnlkSFhkMGk0UHNITlI1Vlo4NXFZQjZVb21IWmxsCnlvMnd2Zzh3UUJ1NkJzVUpERCszS2grR0tnUEUxSU1OMDFPREFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlMrYkNzTm1NNkJjYm5wSWx1NwphZzZxQk1HcGNEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFLZjZPZUMzRm95N0h1ZEUwQ3FHa1pwUnpONVFHCjh5NTZ6ajlIRWdaMjlCVzNiVDJ3RFFsc0VrTWZCL0VhWk9HUnQ0WlVWTmVSSm4xSEZuQnVyQzUzTS9ReWFMRmQKSm9FMTRsZ2puc0p2WXZJc0FSSHAyaFpIbnNGWVpHU1o3VjFnQWMxV1hiTElHSTFjMnIydEFNdTRpOFlibHBVUQpuZENGTG12djYzY0tDZU9LSkRKSTdDU01BSmhZVm96OGJVMFl2NmRSM1ZxOVRTMEdzbU53OExyOUpxeG1saEFKCnJ6eEd1d1V1b2tZQ0p3TUNOeHBOQXlTZDZ0RVFnL1F5TjBXYkhURFlIdzN6TEo3M0RiMFlLV2lEeEx1THJscUsKNWE0dkM0RkIzNXZGM00xclVpdEcwLzZOeTlYZDdKZkYzL3o2K1V5MFN6TUt5S2pqZFE1bXQ4dFJHQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://8d8d1995-5e1f-4555-b317-210e944e3733.k8s.ondigitalocean.com
  name: do-sgp1-seanmovies
contexts:
- context:
    cluster: do-sgp1-seanmovies
    user: do-sgp1-seanmovies-admin
  name: do-sgp1-seanmovies
current-context: do-sgp1-seanmovies
kind: Config
preferences: {}
users:
- name: do-sgp1-seanmovies-admin
  user:
    token: ""  # set via KUBECONFIG env or replace with your DigitalOcean token
