apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: serving-update-cron
  namespace: argo
spec:
  schedules:
    - "0 2 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowSpec:
    workflowTemplateRef:
      name: serving-update-cron
