apiVersion: batch/v1
kind: Job
metadata:
  name: train-gnn
  namespace: argo
spec:
  template:
    metadata:
      labels:
        app: train-gnn
    spec:
      containers:
      - name: train-gnn
        image: trlocne204/train-jobs:latest
        command: ["python", "/app/train_gnn.py"]
        env:
        - name: MILVUS_HOST
          value: milvus-standalone
        - name: MILVUS_PORT
          value: "19530"
        resources:
          requests:
            memory: "2Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "8000m"
      restartPolicy: OnFailure
