replicaCount: 1

image:
  repository: trlocne204/recsys-ui
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

env:
  recsysApiBaseUrl: "http://serving.serving.svc.cluster.local:8000"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

nodeSelector: {}
tolerations: []
affinity: {}
