FROM ghcr.io/mlflow/mlflow:v3.11.1

WORKDIR /app

# Install additional dependencies
RUN apt-get -y update && \
    apt-get -y install curl python3-dev build-essential pkg-config && \
    rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --upgrade pip && \
    pip install boto3 pyyaml kubernetes

CMD ["bash"]
