apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recsys-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/trlocne/end-to-end-recsys-movies.git
    targetRevision: main
    path: deployments/helm/platform/monitoring
    helm:
      releaseName: recsys-monitoring
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: Prometheus
      jsonPointers:
        - /status/terminatingReplicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status/terminatingReplicas
