apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recsys-ui.fullname" . }}
  labels:
    {{- include "recsys-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "recsys-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recsys-ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: recsys-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: RECSYS_API_BASE_URL
              value: {{ .Values.env.recsysApiBaseUrl | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
