namespace: mlflow
createNamespace: true

aws:
  secretName: aws-creds
  region: ap-southeast-1
  accessKey: ""   # set via: kubectl create secret generic aws-creds ... -n mlflow
  secretKey: ""   # KHÔNG commit credentials vào đây
  s3:
    bucket: "recsys-moivelens"

minio:
  enabled: false

postgres:
  enabled: true
  image: postgres:13
  user: postgres
  password: ""   # set via K8s Secret
  database: mlflow
  nodeSelector:
    karpenter.sh/nodepool: system
    kubernetes.io/os: linux
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  service:
    port: 5432

mlflow:
  image: trlocne204/mlflow:latest
  imagePullPolicy: Always
  serviceAccountName: ""
  workers: 1
  allowedHosts:
    - "*"
  corsAllowedOrigins:
    - "*"
  nodeSelector:
    karpenter.sh/nodepool: system
    kubernetes.io/os: linux
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
      effect: NoSchedule
  backendStoreUri: "postgresql+psycopg2://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/mlflow"
  artifactRoot: "s3://recsys-moivelens/processed/mlflow-artifacts"
  s3_endpoint: ""
  service:
    type: ClusterIP
    port: 5000
  resources:
    limits:
      cpu: "1"
      memory: "2Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

storageClass:
  create: true
  name: ebs-sc
  provisioner: ebs.csi.eks.amazonaws.com
  reclaimPolicy: Retain
  allowVolumeExpansion: true
  volumeBindingMode: WaitForFirstConsumer
  parameters:
    csi.storage.k8s.io/fstype: xfs
    type: gp3
    encrypted: "true"
    tagSpecification_1: Name=ebs-sc
    tagSpecification_2: CostCentre=recsys

persistence:
  enabled: true
  storageClassName: ebs-sc
  mlflowSize: 20Gi
  postgresSize: 20Gi
