apiVersion: batch/v1
kind: Job
metadata:
  name: indexing
  namespace: argo
spec:
  template:
    metadata:
      labels:
        app: indexing
    spec:
      containers:
      - name: indexing
        image: trlocne204/indexing:latest
        env:
        - name: MILVUS_HOST
          value: milvus-standalone
        - name: MILVUS_PORT
          value: "19530"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "4000m"
      restartPolicy: OnFailure
